# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_app', '0003_auto_20170419_0831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('user', 'book')]),
        ),
    ]
