# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_auto_20170420_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='review',
        ),
    ]
